---
--- Generated by Luanalysis
--- Created by Lyr.
--- DateTime: 1/8/2021 5:30 PM
---

--[[
  CFG:    cfg.duration    integer
          cfg.modifiers   StatModifier[]
  INPUT:  data.?    ?
--]]


if not Modsys then error("This script isn't supposed to be require'd yourself lol.") end
---@type Modsys, Action
local Modsys, Action = Modsys, Action

---@class ModifyStats : Action
local ModifyStats = Action.new()

function ModifyStats:init()   -- TODO CHECK FOR -1 DURATION!!!
  self.storage.activeTimer = self:storageDefault("activeTimer", 0)
  if self.storage.activeTimer > 0 then
    self:run({})
  end
end

function ModifyStats:update(dt)
  self.storage.activeTimer = math.max(0, self.storage.activeTimer - dt)
  if self.statGid and self.storage.activeTimer == 0 then
    effect.removeStatModifierGroup(self.statGid)
    self.statGid = nil
  end
end

function ModifyStats:uninit()
end

function ModifyStats:run(_)
  -- todo check if nil
  self.storage.activeTimer = self.cfg.duration
  if not self.statGid then
    self.statGid = effect.addStatModifierGroup(self.cfg.modifiers)
  end
end
