---
--- Generated by Luanalysis
--- Created by Lyr.
--- DateTime: 1/10/2021 4:42 PM
---

--[[
  CFG:    cfg.statusEffects     Effect[]
          cfg.useDataTarget     boolean   false   use targetEntityId from data instead of self
  INPUT:  data.targetEntityId   EntityId
--]]

if not Modsys then error("This script isn't supposed to be require'd yourself lol.") end
---@type Modsys, Action
local Modsys, Action = Modsys, Action

---@class ApplyEffects : Action
local ApplyEffects = Action.new()

function ApplyEffects:init()
  -- normal init
end

function ApplyEffects:update(dt)
  -- self:emit()
end

function ApplyEffects:uninit()
  -- normal uninit
end

function ApplyEffects:run(data)
  if self.cfg.useDataTarget then
    if not data.targetEntityId then return end
    for _, effect in ipairs(self.cfg.statusEffects) do
      local name = effect
      local duration
      if type(effect) == "table" then
        name = effect.effect
        duration = effect.duration
      end
      -- TODO, detect starryPy instance and do another method instead? Not an issue atm
      world.sendEntityMessage(data.targetEntityId, "applyStatusEffect", name, duration, entity.id())
    end
  else
    status.addEphemeralEffects(self.cfg.statusEffects, entity.id())
  end
end
