---
--- Generated by Luanalysis
--- Created by Lyr.
--- DateTime: 1/8/2021 5:30 PM
---

--[[
  CFG:    item        itemDesc  item to spawn
          baseAmount  int       base number of items to spawn
          factor      var       variable to multiply to the base amount, optional
          useDataPos  boolean   false   use data as damageRequest type to get pos/entity pos from targetEntityId
          parameters  table     {}  item parameters
          randomVel   boolean   false   spawned item will have random velocity?
          pickupDelay number    0   delay before item can be picked up

  INPUT:  position or targetEntityId    if useDataPos
          <var>
--]]


if not Modsys then error("This script isn't supposed to be require'd yourself lol.") end
---@type Modsys, Action
local Modsys, Action = Modsys, Action

---@class SpawnItem : Action
local SpawnItem = Action.new()

function SpawnItem:init()

end

function SpawnItem:update(dt)
  -- persistence etc
end

function SpawnItem:uninit()
  -- normal uninit
end

function SpawnItem:run(data)
  local spawnPos = self.cfg.useDataPos and (data.position or world.entityPosition(data.targetEntityId)) or mcontroller.position()
  local randVel = self.cfg.randomVel and
      {-10 + math.random() * 20, math.random() * 15} or
      {0, 0}
  -- if factor present in config and not in data, 0
  -- if factor config not specified, mul by 1
  local amount = self.cfg.baseAmount * (self.cfg.factor and (data[self.cfg.factor] or 0) or 1)
  world.spawnItem(
      self.cfg.item,
      spawnPos,
      amount,
      self.cfg.parameters or {},
      randVel,
      self.cfg.pickupDelay or 0
  )
end
