---
--- Generated by Luanalysis
--- Created by Lyr.
--- DateTime: 1/21/2021 6:55 PM
---

--[[
  CFG:    cfg.which     ModuleNames[]
  INPUT:  data.?    ?
--]]

if not Modsys then error("This script isn't supposed to be require'd yourself lol.") end
---@type Modsys, Action
local Modsys, Action = Modsys, Action

---@class ResetStores : Action
local ResetStores = Action.new()

function ResetStores:init()
  -- normal init
end

function ResetStores:update(dt)
  -- persistence etc
end

function ResetStores:uninit()
  -- normal uninit
end

function ResetStores:run(_)
  for _, moduleName in ipairs(self.cfg.which) do
    if not Modsys.resetStorage(moduleName) then Modsys.logWarn("%s is not a valid module name.", moduleName) end
  end
end
