---
--- Generated by Luanalysis
--- Created by Lyr.
--- DateTime: 1/25/2021 9:50 PM
---

--[[
  EVENT:  <type>
  CFG:    resource  Resource
          val   float                       Sign determines if add or subtract.
          type  "relative" | "set"          To add or subtract current value (relative); or to set the value itself
          form  "exact" | "percentage"      Treat value as is, or as a percentage of the maximum.

--]]



--[[
  INPUT:  type/field  type/*
  CFG:    name  type
--]]

if not Modsys then error("This script isn't supposed to be require'd yourself lol.") end
---@type Modsys, Action
local Modsys, Action = Modsys, Action

---@class ModifyResource : Action
local ModifyResource = Action.new()

function ModifyResource:init()
  self.enabled = status.isResource(self.cfg.resource)   -- todo: do resources appear and disappear, or permanent?
  self.resourceFunction = status[
      (self.cfg.type == "set" and "set" or "modify") ..
      "Resource" ..
      (self.cfg.form == "percentage" and "Percentage" or "")
  ]

  -- todo: duration  float  lerp the modification for duration (Needs a 'good' delta to be smooth)
end

function ModifyResource:update(dt)
end

function ModifyResource:uninit()
end

function ModifyResource:run(data)
  if self.enabled then self.resourceFunction(self.cfg.resource, self.cfg.val) end
end
