---
--- Generated by Luanalysis
--- Created by Lyr.
--- DateTime: 1/27/2021 1:36 PM
---


--[[
  EVENT:  {}
--]]

if not Modsys then error("This script isn't supposed to be require'd yourself lol.") end
---@type Modsys, Event
local Modsys, Event = Modsys, Event

---@class OnInit : Event
local OnInit = Event.new()

function OnInit:init()
  self:emit({})
end

function OnInit:update(dt)
end

function OnInit:uninit()
end
