---
--- Generated by Luanalysis
--- Created by Lyr.
--- DateTime: 12/25/2020 8:23 PM
---

--[[
  EVENT:  <type>
  CFG:    stat  Resource
          op    "<" ">" "="
          val   float
          as    "percentage" | "absolute"     -- TODO : implement relative
--]]

if not Modsys then error("This script isn't supposed to be require'd yourself lol.") end
---@type Modsys, Event
local Modsys, Event = Modsys, Event

---@class OnStatThreshold : Event
local OnStatThreshold = Event.new()

function OnStatThreshold:init()
  self.storage.hasEmitted = self:storageDefault("hasEmitted", false)

  local sr, srm = status.resource, status.resourceMax
  local l = self.cfg.as == "absolute" and sr or function(a) return sr(a)/srm(a) end
  local r, s = self.cfg.val, self.cfg.stat

  if self.cfg.op == "<" then
    self.fn = function() return l(s) < r end
  elseif self.cfg.op == ">" then
    self.fn = function() return l(s) > r end
  else
    self.fn = function() return l(s) == r end
  end
end

function OnStatThreshold:update(dt)
  if self.storage.hasEmitted then
    if not self.fn() then
      self.storage.hasEmitted = false
    end
  elseif self.fn() then
    self:emit({statValue = status.resource(self.cfg.stat)})
    self.storage.hasEmitted = true
  end
end

function OnStatThreshold:uninit()
  -- normal uninit
end
