---
--- Generated by Luanalysis
--- Created by Lyr.
--- DateTime: 1/10/2021 10:25 AM
---

--[[
  EVENT:  DamageNotification
  CFG:    includePassives     boolean   false     punchies and... whatever you keep in your ship maybe
          onlyKill            boolean   false     only emit when enemy killed
--]]

if not Modsys then error("This script isn't supposed to be require'd yourself lol.") end
---@type Modsys, Event
local Modsys, Event = Modsys, Event

require "/scripts/status.lua"

---@class OnAttack : Event
local OnAttack = Event.new()

local function isEnemy(notif)
  local selfTeam = entity.damageTeam()
  local otherTeam = world.entityDamageTeam(notif.targetEntityId)
  local opposing = otherTeam and    -- check if other entity exists
      ((selfTeam.type == "friendly" and otherTeam.type == "enemy") or
          (selfTeam.type == "enemy" and otherTeam.type == "friendly"))
  return opposing and selfTeam.team ~= otherTeam.team
end

function OnAttack:init(re)
  local observedHitType = self.cfg.onlyKill and "Kill" or "Hit"
  self.listener = damageListener("inflictedDamage", function(notifications)
    for _, n in pairs(notifications) do
      if n.hitType == observedHitType and n.healthLost > 0 and (self.cfg.includePassives or isEnemy(n)) then
        self:emit(n)
      end
    end
  end)
end

function OnAttack:update(dt, re)
  self.listener:update()
end

function OnAttack:uninit()
  -- normal uninit
end
