---
--- Generated by Luanalysis
--- Created by Lyr.
--- DateTime: 1/27/2021 1:36 PM
---


--[[
  EVENT:  {}
  CFG:    duration      float     time in seconds between events
          noStoreRead   boolean   don't use stored time
--]]

if not Modsys then error("This script isn't supposed to be require'd yourself lol.") end
---@type Modsys, Event
local Modsys, Event = Modsys, Event

---@class Timer : Event
local Timer = Event.new()

function Timer:init()
  self.storage.timer = self:storageDefault("timer", self.cfg.duration)
  self.storage.timer = self.cfg.noStoreRead and self.cfg.duration or self.storage.timer
  if self.storage.timer > self.cfg.duration then self.storage.timer = self.cfg.duration end
end

function Timer:update(dt)
  self.storage.timer = self.storage.timer - dt
  if (self.storage.timer < 0) then
    self.storage.timer = self.cfg.duration
    self:emit({})
  end
  sb.setLogMap("modsys." .. self._name, "Til' next: %s/%s", self.storage.timer, self.cfg.duration)
end

function Timer:uninit()
end
