---
--- Generated by Luanalysis
--- Created by Lyr.
--- DateTime: 1/10/2021 6:50 PM
---

--[[
  CFG:    cfg.duration  number
  INPUT:  -
--]]

if not Modsys then error("This script isn't supposed to be require'd yourself lol.") end
---@type Modsys, Filter
local Modsys, Filter = Modsys, Filter

---@class Cooldown : Filter
local Cooldown = Filter.new()

function Cooldown:init()
  self.storage.cooldownTimer = self:storageDefault("cooldownTimer", 0)
  if self.storage.cooldownTimer > self.cfg.duration then self.storage.cooldownTimer = self.cfg.duration end
end

function Cooldown:update(dt)
  self.storage.cooldownTimer = math.max(0, self.storage.cooldownTimer - dt)
  Modsys.debugMap("Cooldown: %s/%s", self.storage.cooldownTimer, self.cfg.duration)
end

function Cooldown:uninit()

end

function Cooldown:process(data)
  if self.storage.cooldownTimer > 0 then return end
  self.storage.cooldownTimer = self.cfg.duration
  return data   -- returning the data means the filter passed.
end
